### ISSUE TITLE
mood.msgpack-0.1.0, pypy setup.py install, compiler error !

### ISSUE THREAD

**Issue by blacksun1977** [lekma/mood.msgpack#1]
[root@fd70c61b7923 mood.msgpack-0.1.0]# pypy setup.py install   
running install
running bdist_egg
running egg_info
writing mood.msgpack.egg-info/PKG-INFO
writing dependency_links to mood.msgpack.egg-info/dependency_links.txt
writing namespace_packages to mood.msgpack.egg-info/namespace_packages.txt
writing top-level names to mood.msgpack.egg-info/top_level.txt
reading manifest file 'mood.msgpack.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.rst'
writing manifest file 'mood.msgpack.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'msgpack' extension
cc -pthread -DNDEBUG -O2 -fPIC -DPKG_VERSION="0.1.0" -I/usr/local/pypy59/include -c src/msgpack.c -o build/temp.linux-x86_64-2.7/src/msgpack.o
In file included from src/msgpack.c:28:
src/helpers/helpers.c: In function ‘_PyModule_GetState’:
src/helpers/helpers.c:160: warning: assignment makes pointer from integer without a cast
src/helpers/helpers.c: At top level:
src/helpers/helpers.c:168: error: expected ‘)’ before ‘*’ token
src/helpers/helpers.c: In function ‘_PyErr_SetFromErrnoWithFilename’:
src/helpers/helpers.c:191: warning: passing argument 2 of ‘PyPyErr_SetFromErrnoWithFilename’ discards qualifiers from pointer target type
/usr/local/pypy59/include/pypy_decl.h:229: note: expected ‘char *’ but argument is of type ‘const char *’
src/helpers/helpers.c: In function ‘__PyObject_GC_New’:
src/helpers/helpers.c:223: warning: assignment makes pointer from integer without a cast
src/helpers/helpers.c: In function ‘__PyByteArray_Grow’:
src/helpers/helpers.c:250: error: ‘PyByteArrayObject’ has no member named ‘ob_alloc’
src/helpers/helpers.c:251: error: ‘PyByteArrayObject’ has no member named ‘ob_alloc’
src/helpers/helpers.c:251: error: ‘PyByteArrayObject’ has no member named ‘ob_alloc’
src/helpers/helpers.c:259: error: ‘PyByteArrayObject’ has no member named ‘ob_bytes’
src/helpers/helpers.c:263: error: ‘PyByteArrayObject’ has no member named ‘ob_bytes’
src/helpers/helpers.c:263: error: ‘PyByteArrayObject’ has no member named ‘ob_start’
src/helpers/helpers.c:264: error: ‘PyByteArrayObject’ has no member named ‘ob_alloc’
src/helpers/helpers.c:266: error: ‘PyByteArrayObject’ has no member named ‘ob_bytes’
src/helpers/helpers.c:268: error: ‘PyByteArrayObject’ has no member named ‘ob_bytes’
src/msgpack.c:37:2: error: #error msgpack needs <endian.h> or <sys/endian.h>
src/msgpack.c: At top level:
src/msgpack.c:42: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘msgpack_def’
src/msgpack.c: In function ‘_pack_class’:
src/msgpack.c:238: error: ‘__module__’ undeclared (first use in this function)
src/msgpack.c:238: error: (Each undeclared identifier is reported only once
src/msgpack.c:238: error: for each function it appears in.)
src/msgpack.c:239: error: ‘__qualname__’ undeclared (first use in this function)
src/msgpack.c:242: error: ‘PyId___module__’ undeclared (first use in this function)
src/msgpack.c:243: error: ‘PyId___qualname__’ undeclared (first use in this function)
src/msgpack.c: In function ‘_pack_singleton’:
src/msgpack.c:257: error: ‘__reduce__’ undeclared (first use in this function)
src/msgpack.c:260: error: ‘PyId___reduce__’ undeclared (first use in this function)
src/msgpack.c: In function ‘__pack_set__’:
src/msgpack.c:625: error: ‘Py_hash_t’ undeclared (first use in this function)
src/msgpack.c:625: error: expected ‘;’ before ‘hash’
src/msgpack.c:630: error: ‘hash’ undeclared (first use in this function)
src/msgpack.c: In function ‘PyUnicode_Pack’:
src/msgpack.c:727: warning: assignment makes pointer from integer without a cast
src/msgpack.c:735:1: warning: "PyTuple_Pack" redefined
In file included from /usr/local/pypy59/include/Python.h:76,
                 from src/msgpack.c:24:
/usr/local/pypy59/include/pypy_macros.h:20:1: warning: this is the location of the previous definition
src/msgpack.c: In function ‘PyDict_Pack’:
src/msgpack.c:743: error: ‘PyDictObject’ has no member named ‘ma_used’
src/msgpack.c: In function ‘PyList_Pack’:
src/msgpack.c:817: warning: passing argument 3 of ‘_pack_sequence’ makes pointer from integer without a cast
src/msgpack.c:653: note: expected ‘struct PyObject **’ but argument is of type ‘int’
src/msgpack.c: In function ‘PyObject_Pack’:
src/msgpack.c:851: error: ‘__reduce__’ undeclared (first use in this function)
src/msgpack.c:856: error: ‘PyId___reduce__’ undeclared (first use in this function)
src/msgpack.c: In function ‘_unpack_registered’:
src/msgpack.c:1112: error: ‘msgpack_def’ undeclared (first use in this function)
src/msgpack.c: In function ‘__PyClass_ErrFromBuffer’:
src/msgpack.c:1413: error: ‘builtins’ undeclared (first use in this function)
src/msgpack.c:1418: error: ‘PyId_builtins’ undeclared (first use in this function)
src/msgpack.c: In function ‘_PyObject_SetState’:
src/msgpack.c:1477: error: ‘__setstate__’ undeclared (first use in this function)
src/msgpack.c:1478: error: ‘__dict__’ undeclared (first use in this function)
src/msgpack.c:1484: error: ‘PyId___setstate__’ undeclared (first use in this function)
src/msgpack.c:1492: error: ‘PyId___dict__’ undeclared (first use in this function)
src/msgpack.c: In function ‘_PyObject_Extend’:
src/msgpack.c:1556: error: ‘extend’ undeclared (first use in this function)
src/msgpack.c:1559: error: ‘PyId_extend’ undeclared (first use in this function)
src/msgpack.c: In function ‘_PyObject_Update’:
src/msgpack.c:1635: error: ‘update’ undeclared (first use in this function)
src/msgpack.c:1638: error: ‘PyId_update’ undeclared (first use in this function)
src/msgpack.c: At top level:
src/msgpack.c:2193: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘msgpack_def’
src/msgpack.c: In function ‘PyInit_msgpack’:
src/msgpack.c:2212: error: ‘msgpack_def’ undeclared (first use in this function)
src/msgpack.c:2227: warning: ‘return’ with a value, in function returning void
error: command 'cc' failed with exit status 1

**Comment by lekma** [comment]
can you build cpython based modules with pypy? (i really am not very familiar with pypy, last time i checked it out must have been 2 years ago)

for reference: https://github.com/python/cpython/blob/3.5/Include/bytearrayobject.h#L25

**Comment by lekma** [comment]
or is it that pypy implements only the limited api?
